name: Pull Request
description: 提取請求
title: "[PR]: "
labels: "pull request"
body:
  - type: markdown
    attributes:
      value: |
        感謝您的貢獻！請按照以下格式填寫您的提取請求。

  - type: textarea
    id: issues
    attributes:
      label: Issue
      description: 請填寫 Issue 編號。
      placeholder: "#123"
    validations:
      required: true

  - type: checkboxes
    id: pr_type
    attributes:
      label: 變更類型
      description: 請選擇此次提交的類型。
      options:
        - label: feature
        - label: bug
        - label: documentation
        - label: test
    validations:
      required: true

  - type: textarea
    id: pr_description
    attributes:
      label: 提取內容描述
      description: 請詳細描述此次提取的內容，並說明其背景和目的。
      placeholder: 提取內容描述
    validations:
      required: true

  - type: dropdown
    id: scope_of_impact
    attributes:
      label: 影響範圍
      description: 請選擇此次變更的影響範圍。
      options:
        - 無
        - 小範圍變更
        - 模組級變更
        - 全系統變更
    validations:
      required: true

  - type: textarea
    id: testing_instructions
    attributes:
      label: 測試說明
      description: 請提供測試此次變更的說明，讓 reviewer 可以根據您的步驟進行測試。
      placeholder: 測試說明
    validations:
      required: false

  - type: checkboxes
    id: pr_checklist
    attributes:
      label: PR 檢查清單
      description: 提交 PR 前請確認完成以下檢查。
      options:
        - label: 代碼已經過自我審查
          required: true
        - label: 測試已通過且結果符合預期
          required: true
        - label: 相關文檔已更新
